import type { Project } from "@/lib/types"

export const projects: Project[] = [
  {
    id: "1",
    title: 'Ashishcrafts',
    description: 'Rooted in the heart of the Himalayas and bridging cultures through craftsmanship, Ashish Crafts and Creations is a globally recognized manufacturer and exporter of exquisite handmade woolen felt products. With a dual presence in Nepal (where our artisans craft every piece) and the USA (where we connect with the world), we unite ancient traditions with modern innovation to create ethical, eco-friendly, and uniquely beautiful products that honor Nepal’s rich cultural heritage.',
    image: '/image/products/ashishcrafts.jpg',
    tags: ['Laravel', 'Bootstrap', 'JavaScript', 'PHP'],
    demo: 'https://ashishcrafts.com/',
  },
  {
    id: "2",
    title: 'International Restwell',
    description: 'Experience the difference with our team of passionate and innovative leaders in the industry.',
    image: '/image/products/InternationalRestwell.jpg',
    tags: ['Laravel', 'Bootstrap', 'JavaScript', 'PHP'],
    demo: 'https://www.irwservices.com.au/',
  },
  {
    id: "3",
    title: 'उच्च शिक्षालय तथा माध्यमिक विद्यालय सङ्घ नेपाल',
    description: 'Higher Institutions and Secondary Schools’ Association Nepal (HISSAN) was established in 2053 BS (1997 AD) as an umbrella organization of private schools and colleges that are running classes from grade nine to university level throughout Nepal.',
    image: '/image/products/hissankathmandu.jpg',
    tags: ['Laravel', 'Bootstrap', 'JavaScript', 'PHP'],
    demo: 'https://hissankathmandu.org/',
  },
  {
    id: "4",
    title: 'Zin Pesa Nepal',
    description: 'Established in 2021 A.D. by professionals having decade-long experience and expertise in the abroad education counseling sector, Z. Pesa Nepal Pvt. Ltd. (Zin Pesa Nepal) is one of the leading and most motivating education consultancies incorporated under the office of the Company Registrar and Ministry of Social Development of Bagmati Province, Nepal. Zin is authorized to hold education consultancy services, test preparation classes, and language classes.',
    image: '/image/products/zinpesanepal.jpg',
    tags: ['Laravel', 'Bootstrap', 'JavaScript', 'PHP'],
    demo: 'https://zinpesanepal.com/',
  },
  {
    id: "6",
    title: 'Garima Florist',
    description: 'Garima Florist & Events is an event planning company doing business since 15 years, providing complete planning, consulting, and supervision of any events. Garima Florist & Events provides its clients with spectacular events through creativity and uniqueness based on individual tastes and preferences with the ultimate goal of making your design-specific event a most elegant, unique, and memorable experience.',
    image: '/image/products/garimaflorist.jpg',
    tags: ['Laravel', 'Bootstrap', 'JavaScript', 'PHP'],
    demo: 'https://garimaflorist.com/',
  },
  {
    id: "5",
    title: 'Metamax Studio',
    description: 'Delivering wholesome integrated design & marketing solutions to clients all over the world.',
    image: '/image/products/metamaxstudio.jpg',
    tags: ['Laravel', 'Bootstrap', 'JavaScript', 'PHP'],
    demo: 'https://metamaxstudio.com.au/',
  },
  {
    id: "7",
    title: 'Kamkaaz',
    description: 'Looking for work? Need to hire someone? Kamkaaz is your all-in-one platform that connects job seekers and employers across Nepal—quickly, simply, and fairly. Whether you’re educated or uneducated, skilled or unskilled, experienced or just starting out, Kamkaaz is built for everyone, without discrimination. We believe everyone deserves a chance, and we’re here to make it happen.',
    image: '/image/products/kamkaaz.jpg',
    tags: ['Laravel', 'PHP'],
    demo: 'https://play.google.com/store/apps/details?id=com.dwashkarma.kamkaaz&pcampaignid=web_share',
  },
  {
    id: "8",
    title: 'Naasa X',
    description: 'Naasa X: The Future of Trading is set to ignite your trading journey like never before.',
    image: '/image/products/x-naasa.jpg',
    tags: ['NextJs', 'Shadcn', 'TradingView', 'Tailwind CSS'],
    demo: 'https://x.naasasecurities.com.np/',
  },
  {
    id: "9",
    title: 'Waterflow Technology',
    description: 'Waterflow Technology is a leading provider of innovative technology solutions for the water and wastewater industry. Our mission is to help our clients optimize their operations, reduce costs, and improve service delivery through the use of advanced technology.',
    image: '/image/products/waterflow.jpg',
    tags: ['Wordpres', 'PHP', 'Boostrap'],
    demo: 'https://waterflow.technology/',
  }
]
